[build]
  command = "CI= npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_FLAGS = "--legacy-peer-deps"

[build.processing]
  skip_processing = false

# 添加重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 处理404页面
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404